# Generated by Django 5.0.7 on 2024-07-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'ordering': ['group', 'key'], 'verbose_name': 'Configuration', 'verbose_name_plural': 'Configurations'},
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='schema',
        ),
        migrations.AlterField(
            model_name='configuration',
            name='value',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
