# Generated by Django 5.0.7 on 2024-08-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_configuration_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxrate',
            name='taxclass',
        ),
        migrations.DeleteModel(
            name='TaxClass',
        ),
        migrations.DeleteModel(
            name='TaxRate',
        ),
    ]
