# Generated by Django 5.0.7 on 2024-08-01 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
                ('unit', models.CharField(max_length=5)),
                ('value', models.FloatField(blank=True)),
            ],
            options={
                'verbose_name': 'Weight Class',
                'verbose_name_plural': 'Weight Classes',
            },
        ),
        migrations.CreateModel(
            name='LengthClass',
            fields=[
                ('weightclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master.weightclass')),
            ],
            options={
                'verbose_name': 'Length Class',
                'verbose_name_plural': 'Length Classes',
            },
            bases=('master.weightclass',),
        ),
    ]
