# Generated by Django 5.0.7 on 2024-08-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=8)),
                ('symbol_left', models.CharField(blank=True, max_length=8)),
                ('symbol_right', models.CharField(blank=True, max_length=8)),
                ('decimal_places', models.PositiveSmallIntegerField()),
                ('value', models.FloatField(help_text='The value of your default currency in the current currency unit. Set to 1 for your default currency.')),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
