# Generated by Django 5.0.7 on 2024-08-01 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Stock Status',
                'verbose_name_plural': 'Stock Statuses',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('stockstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master.stockstatus')),
            ],
            options={
                'verbose_name': 'Order Status',
                'verbose_name_plural': 'Order Statuses',
            },
            bases=('master.stockstatus',),
        ),
        migrations.CreateModel(
            name='ReturnAction',
            fields=[
                ('stockstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master.stockstatus')),
            ],
            options={
                'verbose_name': 'Return Action',
                'verbose_name_plural': 'Return Actions',
            },
            bases=('master.stockstatus',),
        ),
        migrations.CreateModel(
            name='ReturnReason',
            fields=[
                ('stockstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master.stockstatus')),
            ],
            options={
                'verbose_name': 'Return Reason',
                'verbose_name_plural': 'Return Reasons',
            },
            bases=('master.stockstatus',),
        ),
        migrations.CreateModel(
            name='ReturnStatus',
            fields=[
                ('stockstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master.stockstatus')),
            ],
            options={
                'verbose_name': 'Return Status',
                'verbose_name_plural': 'Return Statuses',
            },
            bases=('master.stockstatus',),
        ),
        migrations.CreateModel(
            name='SubscriptionStatus',
            fields=[
                ('stockstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master.stockstatus')),
            ],
            options={
                'verbose_name': 'Subscription Status',
                'verbose_name_plural': 'Subscription Statuses',
            },
            bases=('master.stockstatus',),
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.FloatField()),
                ('type', models.CharField(blank=True, choices=[('P', 'Percentage'), ('F', 'Fixed Amount')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geozone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.geozone')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
            },
        ),
    ]
