# Generated by Django 5.0.7 on 2024-08-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('master', '0006_stockstatus_orderstatus_returnaction_returnreason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrate',
            name='customergroups',
            field=models.ManyToManyField(to='customer.customergroup'),
        ),
    ]
