# Generated by Django 5.0.7 on 2024-08-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_taxclass_alter_taxrate_customergroups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('geocode', models.CharField(blank=True, max_length=15)),
                ('image', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d')),
                ('opening_time', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Store Location',
                'verbose_name_plural': 'Store Locations',
            },
        ),
    ]
