# Generated by Django 5.0.7 on 2024-08-01 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sort_order', models.PositiveSmallIntegerField(blank=True, default=1)),
            ],
            options={
                'verbose_name': 'Filter Group',
                'verbose_name_plural': 'Filter Groups',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sort_order', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('filtergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.filtergroup')),
            ],
            options={
                'verbose_name': 'Filter',
                'verbose_name_plural': 'Filters',
            },
        ),
    ]
