# Generated by Django 5.0.7 on 2024-08-01 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(blank=True, choices=[('Coose', [('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox')]), ('Input', [('text', 'Text'), ('textarea', 'Textarea')]), ('File', [('file', 'File')]), ('Date', [('date', 'Date'), ('time', 'Time'), ('datetime', 'Datetime')])], default='select', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(blank=True, default=1)),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.RemoveField(
            model_name='filter',
            name='filtergroup',
        ),
        migrations.CreateModel(
            name='FilterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sort_order', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.filter')),
            ],
            options={
                'verbose_name': 'Filter Value',
                'verbose_name_plural': 'Filter Values',
            },
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(limit_choices_to={'type__in': ['select', 'radio', 'checkbox']}, on_delete=django.db.models.deletion.CASCADE, to='catalog.option')),
            ],
            options={
                'verbose_name': 'Option Value',
                'verbose_name_plural': 'Option Values',
            },
        ),
        migrations.DeleteModel(
            name='FilterGroup',
        ),
    ]
