# Generated by Django 5.0.7 on 2024-08-01 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_optionvalue_image_optionvalue_sort_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sort_order', models.PositiveSmallIntegerField(blank=True, default=1)),
            ],
            options={
                'verbose_name': 'Attribute Group',
                'verbose_name_plural': 'Attribute Groups',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sort_order', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('attributegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.attributegroup')),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
            },
        ),
    ]
